version: 2

project_name: vmware-exporter

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./
    binary: vmware-exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    # 生成格式如: vmware-exporter-v0.1.16-linux-amd64.tar.gz
    name_template: "{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"