{
 "title": "vCenter View",
 "tags": [
  "vmware",
  "vcenter"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "20s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(vmware_vcenter_info,job)"
    }
   },
   {
    "name": "target_type",
    "label": "Target Type",
    "query": {
     "query": "label_values(vmware_target_info{job=\"$job\"}, type)"
    }
   },
   {
    "name": "vcenter",
    "label": "vCenter",
    "query": {
     "query": "label_values(vmware_target_info{job=\"$job\", type=~\"$target_type\"}, target)"
    }
   },
   { "name": "top", "label": "Top", "query": "5,10,20,30,40,50,100" }
  ]
 },
 "panels": [
  {
   "title": "Hosts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n    (vmware_host_info{vcenter=~\"$vcenter\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Running VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  (vmware_vm_info{vcenter=~\"$vcenter\"})\n  and on(vcenter, vmmo) vmware_vm_power_state{state=\"poweredOn\"}\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  vmware_host_cpu_usage_hertz{vcenter=~\"$vcenter\"}\n) /\nsum(\n  (vmware_host_cpu_capacity_hertz{vcenter=~\"$vcenter\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0)) * \n  (vmware_host_cpu_corecount{vcenter=~\"$vcenter\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))\n) \n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vmware_host_mem_consumed_bytes{vcenter=~\"$vcenter\"}) / \nsum((vmware_host_mem_capacity_bytes{vcenter=~\"$vcenter\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0)))\n* 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Provisioned",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    vmware_datastore_capacity_bytes{vcenter=~\"$vcenter\"}\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Storage Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(\n    vmware_datastore_capacity_bytes{vcenter=~\"$vcenter\"}\n  ) -\n  sum(\n    vmware_datastore_free_bytes{vcenter=~\"$vcenter\"}\n  )\n) /\nsum(\n  vmware_datastore_capacity_bytes{vcenter=~\"$vcenter\"}\n)\n* 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    vmware_datastore_free_bytes{vcenter=~\"$vcenter\"}\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "vCenter Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(\n    vmware_vcenter_info{vcenter=~\"$vcenter\"},\n    \"newversion\", \".\",\"version\", \"patch\"\n)",
     "legendFormat": "{{vcenter}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_sys_uptime_seconds{vcenter=~\"$vcenter\", vm=~\"$vcenter\"}  ",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    (vmware_host_cpu_corecount{vcenter=~\"$vcenter\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    (vmware_host_mem_capacity_bytes{vcenter=~\"$vcenter\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Hosts Inventory",
   "type": "table",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\n  label_join(\n    label_replace(\n      vmware_host_hardware_info{vcenter=~\"$vcenter\"},\n      \"vendor\", \"$1\", \"vendor\", \"(.*) .*\"\n    ),\n    \"newmodel\", \" \",\"vendor\", \"model\"\n  ), \"cpu_type\", \"$1 $3 $5\", \"cpu_type\", \"(.*)(\\\\(R\\\\))(.*)(\\\\(R\\\\))(.*) CPU @.*\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(\n    label_replace(\n        vmware_host_software_info{vcenter=~\"$vcenter\"},\n        \"build\", \"($1)\", \"build\", \"(.*)\"\n    ),\n    \"os\",\" \",\"software\",\"version\",\"build\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(vmware_host_cpu_corecount{vcenter=~\"$vcenter\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(vmware_host_cpu_capacity_hertz{vcenter=~\"$vcenter\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(vmware_host_mem_capacity_bytes{vcenter=~\"$vcenter\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))",
     "legendFormat": "__auto"
    },
    {
     "expr": "vmware_host_sys_uptime_seconds{vcenter=~\"$vcenter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(vmware_host_cpu_threadcount{vcenter=~\"$vcenter\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0)) / \n(vmware_host_cpu_corecount{vcenter=~\"$vcenter\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Capacity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    (vmware_host_cpu_capacity_hertz{vcenter=~\"$vcenter\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0)) *\n    (vmware_host_cpu_corecount{vcenter=~\"$vcenter\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    (vmware_host_mem_capacity_bytes{vcenter=~\"$vcenter\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))\n) - \nsum(\n    vmware_host_mem_consumed_bytes{vcenter=~\"$vcenter\"}\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CPU Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    (vmware_host_cpu_capacity_hertz{vcenter=~\"$vcenter\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0)) *\n    (vmware_host_cpu_corecount{vcenter=~\"$vcenter\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))\n) - \nsum(\n    vmware_host_cpu_usage_hertz{vcenter=~\"$vcenter\"}\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory GB per Core",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    (vmware_vm_mem_capacity_bytes{vcenter=~\"$vcenter\"} and on(vcenter, vmmo) vmware_vm_power_state{state=\"poweredOn\"})\n) / \nsum(\n   (vmware_host_cpu_corecount{ vcenter=~\"$vcenter\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CPU Overcommit",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  (vmware_vm_cpu_corecount{vcenter=~\"$vcenter\"} and on(vcenter, vmmo) vmware_vm_power_state{state=\"poweredOn\"})\n)\n/ \nsum(\n  (vmware_host_cpu_threadcount{vcenter=~\"$vcenter\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Overcommit",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  (vmware_vm_mem_capacity_bytes{vcenter=~\"$vcenter\"} and on(vcenter, vmmo) vmware_vm_power_state{state=\"poweredOn\"})\n)\n/\nsum(\n  (vmware_host_mem_capacity_bytes{vcenter=~\"$vcenter\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n  vmware_host_cpu_usage_hertz{vcenter=~\"$vcenter\"}\n) / \nsum(\n  (vmware_host_cpu_capacity_hertz{vcenter=~\"$vcenter\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0)) *\n  (vmware_host_cpu_corecount{vcenter=~\"$vcenter\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))\n) \n* 100",
     "legendFormat": "Usage"
    },
    {
     "expr": "(\navg(\n    vmware_host_cpu_latency_ratio{vcenter=~\"$vcenter\"}\n)\n) * 100",
     "legendFormat": "Latency"
    },
    {
     "expr": "(\navg(\n    sum(\n        rate(vmware_host_cpu_ready_seconds_total{vcenter=~\"$vcenter\"}[$__rate_interval])\n    ) /\n    sum(\n        (vmware_host_cpu_corecount{vcenter=~\"$vcenter\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))\n    ) \n)\n) * 100",
     "legendFormat": "Ready"
    },
    {
     "expr": "(\navg(\n    rate(vmware_host_cpu_costop_seconds_total{vcenter=~\"$vcenter\"}[$__rate_interval])\n)\n) * 100",
     "legendFormat": "Costop"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n    vmware_host_mem_consumed_bytes{vcenter=~\"$vcenter\"}\n) / \nsum(\n    (vmware_host_mem_capacity_bytes{vcenter=~\"$vcenter\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))\n)\n* 100",
     "legendFormat": "Consumed"
    },
    {
     "expr": "sum(\n    vmware_host_mem_active_bytes{vcenter=~\"$vcenter\"}\n) / \nsum(\n    (vmware_host_mem_capacity_bytes{vcenter=~\"$vcenter\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))\n)\n* 100",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(\n    vmware_host_mem_shared_bytes{vcenter=~\"$vcenter\"}\n)/ \nsum(\n    (vmware_host_mem_capacity_bytes{vcenter=~\"$vcenter\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))\n)\n* 100",
     "legendFormat": "Shared"
    },
    {
     "expr": "sum(\n    vmware_host_mem_balloon_bytes{vcenter=~\"$vcenter\"}\n)/ \nsum(\n    (vmware_host_mem_capacity_bytes{vcenter=~\"$vcenter\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))\n)\n* 100",
     "legendFormat": "Ballooned"
    }
   ]
  },
  {
   "title": "Top $top Datastores per Storage Used",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n  $top,\n  max_over_time(\n    (\n      (\n        vmware_datastore_capacity_bytes{vcenter=~\"$vcenter\"}\n        -\n        vmware_datastore_free_bytes{vcenter=~\"$vcenter\"}\n      )\n      /\n      vmware_datastore_capacity_bytes{vcenter=~\"$vcenter\"}\n      * 100\n    )[$__range:]\n  )\n)\n",
     "legendFormat": "{{ds}}"
    }
   ]
  }
 ]
}