{
 "title": "Datastore View",
 "tags": [
  "vmware",
  "datastore"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "20s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(vmware_vcenter_info{},job)"
    }
   },
   {
    "name": "target_type",
    "label": "Target Type",
    "query": {
     "query": "label_values(vmware_target_info{job=\"$job\"}, type)"
    }
   },
   {
    "name": "vcenter",
    "label": "vCenter",
    "query": {
     "query": "label_values(vmware_target_info{job=\"$job\", type=~\"$target_type\"}, target)"
    }
   },
   {
    "name": "datacenter",
    "label": "Datacenter",
    "query": {
     "query": "label_values(vmware_datacenter_info{vcenter=~\"$vcenter\"},dc)"
    }
   },
   {
    "name": "dcmo",
    "query": {
     "query": "label_values(vmware_datacenter_info{vcenter=~\"$vcenter\", dc=~\"$datacenter\"},dcmo)"
    }
   },
   {
    "name": "dcdsfolder",
    "query": {
     "query": "label_values(vmware_folder_info{vcenter=~\"$vcenter\", dcmo=~\"$dcmo\", dc=\"datastore\"},foldermo)"
    }
   },
   {
    "name": "dchostfolder",
    "query": {
     "query": "label_values(vmware_folder_info{vcenter=~\"$vcenter\", dcmo=~\"$dcmo\", dc=\"host\"},foldermo)"
    }
   },
   {
    "name": "datastore",
    "label": "Datastore",
    "query": {
     "query": "label_values(vmware_datastore_info{vcenter=~\"$vcenter\"},ds)"
    }
   },
   {
    "name": "dsmo",
    "query": {
     "query": "label_values(vmware_datastore_info{vcenter=~\"$vcenter\", ds=~\"$datastore\"},dsmo)"
    }
   },
   { "name": "top", "label": "Top", "query": "5,10,20,30,40,50,100" }
  ]
 },
 "panels": [
  {
   "title": "Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_datastore_capacity{vcenter=~\"$vcenter\", dsmo=~\"$dsmo\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Virtual Machines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vmware_vm_datastore_capacity_used{vcenter=~\"$vcenter\", dsmo=~\"$dsmo\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Provisioned",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_datastore_disk_provisioned_latest{vcenter=~\"$vcenter\", dsmo=~\"$dsmo\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_datastore_disk_used_latest{vcenter=~\"$vcenter\", dsmo=~\"$dsmo\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Free",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_datastore_free{vcenter=~\"$vcenter\", dsmo=~\"$dsmo\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Storage Used",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  vmware_datastore_capacity{vcenter=~\"$vcenter\", dsmo=~\"$dsmo\"} -\n  vmware_datastore_free{vcenter=~\"$vcenter\", dsmo=~\"$dsmo\"}\n) /\nvmware_datastore_capacity{vcenter=~\"$vcenter\", dsmo=~\"$dsmo\"}\n* 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overprovisioned",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_datastore_disk_provisioned_latest{vcenter=~\"$vcenter\", dsmo=~\"$dsmo\"} / \nvmware_datastore_capacity * 1024",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Top $top VMs per Datastore Throughput",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n  $top,\n  max_over_time(\n    (\n      (\n        vmware_vm_datastore_read_average{vcenter=~\"$vcenter\"}\n          * on (pfinstance) group_left\n            vmware_datastore_info{vcenter=~\"$vcenter\"}\n      )\n      +\n      (\n        vmware_vm_datastore_write_average{vcenter=~\"$vcenter\"}\n          * on (pfinstance) group_left\n            vmware_datastore_info{vcenter=~\"$vcenter\"}\n      )\n      \n    )[$__range:]\n  )\n)",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "Top $top VMs per Datastore IO",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n  $top,\n  max_over_time(\n    (\n      (\n        vmware_vm_datastore_numberReadAveraged_average{vcenter=~\"$vcenter\"}\n          * on (pfinstance) group_left\n            vmware_datastore_info{vcenter=~\"$vcenter\"}\n      )\n      +\n      (\n        vmware_vm_datastore_numberWriteAveraged_average{vcenter=~\"$vcenter\"}\n          * on (pfinstance) group_left\n            vmware_datastore_info{vcenter=~\"$vcenter\"}\n      )\n    )[$__range:]\n  )\n)\n",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "Top $top VMs Stored on Disk",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n  $top,\n  max_over_time(\n    vmware_vm_datastore_capacity_used{\n      vcenter=~\"$vcenter\"\n    }[$__range:]\n  )\n)\n",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "Top $top VMs per IO Latency",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n  $top,\n  max_over_time(\n    (\n      vmware_vm_datastore_totalReadLatency_average{vcenter=~\"$vcenter\"}\n    )[$__range:]\n  )\n)",
     "legendFormat": "read: {{vm}} "
    },
    {
     "expr": "topk_avg($top,\n    vmware_vm_datastore_totalWriteLatency_average{vcenter=~\"$vcenter\"} * on (pfinstance) group_left \n    vmware_datastore_info{vcenter=~\"$vcenter\", dsmo=\"$dsmo\"}\n) * -1",
     "legendFormat": "write: {{vm}}"
    }
   ]
  },
  {
   "title": "Datastore Troughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "sum(\n  vmware_host_datastore_read_average{vcenter=~\"$vcenter\"} * \n  on (pfinstance) group_left(ds)\n  vmware_datastore_info{vcenter=~\"$vcenter\", dsmo=~\"$dsmo\"}\n)",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(\n  vmware_host_datastore_write_average{vcenter=~\"$vcenter\"} * \n  on (pfinstance) group_left(ds)\n  vmware_datastore_info{vcenter=~\"$vcenter\", dsmo=~\"$dsmo\"}\n) * -1",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Datastore IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(\n  vmware_host_datastore_numberReadAveraged_average{vcenter=~\"$vcenter\"} * \n  on (pfinstance) group_left(ds)\n  vmware_datastore_info{vcenter=~\"$vcenter\", dsmo=~\"$dsmo\"}\n)",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(\n  vmware_host_datastore_numberWriteAveraged_average{vcenter=~\"$vcenter\"} * \n  on (pfinstance) group_left(ds)\n  vmware_datastore_info{vcenter=~\"$vcenter\", dsmo=~\"$dsmo\"}\n) * -1",
     "legendFormat": "Write"
    }
   ]
  }
 ]
}