{
 "title": "Cluster View",
 "tags": [
  "vmware",
  "cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "20s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(vmware_vcenter_info,job)"
    }
   },
   {
    "name": "target_type",
    "label": "Target Type",
    "query": {
     "query": "label_values(vmware_target_info{job=\"$job\"}, type)"
    }
   },
   {
    "name": "vcenter",
    "label": "vCenter",
    "query": {
     "query": "label_values(vmware_target_info{job=\"$job\", type=~\"$target_type\"}, target)"
    }
   },
   {
    "name": "datacenter",
    "label": "Datacenter",
    "query": {
     "query": "label_values(vmware_datacenter_info{vcenter=~\"$vcenter\"},dc)"
    }
   },
   {
    "name": "dcmo",
    "query": {
     "query": "label_values(vmware_datacenter_info{vcenter=~\"$vcenter\", dc=~\"$datacenter\"},dcmo)"
    }
   },
   {
    "name": "dchostfolder",
    "query": {
     "query": "label_values(vmware_folder_info{vcenter=~\"$vcenter\", dcmo=~\"$dcmo\", dc=\"host\"},foldermo)"
    }
   },
   {
    "name": "computemo",
    "query": {
     "query": "label_values(vmware_compute_info{vcenter=~\"$vcenter\", foldermo=~\"$dchostfolder\"}, cmo)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(vmware_cluster_info{vcenter=~\"$vcenter\", foldermo=~\"$dchostfolder\"},vmwcluster)"
    }
   },
   {
    "name": "clustermo",
    "query": {
     "query": "label_values(vmware_cluster_info{vcenter=~\"$vcenter\", foldermo=~\"$dchostfolder\", vmwcluster=~\"$cluster\"}, cmo)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(vmware_host_info{vcenter=~\"$vcenter\", cmo=~\"$computemo|$clustermo\"}, host)"
    }
   },
   {
    "name": "hostmo",
    "query": {
     "query": "label_values(vmware_host_info{vcenter=~\"$vcenter\", cmo=~\"$computemo|$clustermo\", host=~\"$host\"}, hostmo)"
    }
   },
   { "name": "top", "label": "Top", "query": "5,10,20,30,40,50,100" }
  ]
 },
 "panels": [
  {
   "title": "Hosts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((vmware_host_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0)))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((vmware_host_cpu_corecount{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0)))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    (vmware_host_mem_capacity_bytes{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Running VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  (vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"})\n  and on(vcenter, vmmo) vmware_vm_power_state{state=\"poweredOn\"}\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  vmware_host_cpu_usage_hertz{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n) /\nsum(\n  (vmware_host_cpu_capacity_hertz{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0)) * \n  (vmware_host_cpu_corecount{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))\n) \n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vmware_host_mem_consumed_bytes{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}) / \nsum((vmware_host_mem_capacity_bytes{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0)))\n* 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Overcommit",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  (vmware_vm_cpu_corecount{vcenter=~\"$vcenter\"} and on(vcenter, vmmo) vmware_vm_power_state{state=\"poweredOn\"}) * on (vmmo) group_left \n  vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n)\n/ \nsum((vmware_host_cpu_threadcount{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Available",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    (vmware_host_cpu_capacity_hertz{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0)) *\n    (vmware_host_cpu_corecount{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))\n) - \nsum(\n    vmware_host_cpu_usage_hertz{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Compute Capacity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    (vmware_host_cpu_capacity_hertz{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0)) *\n    (vmware_host_cpu_corecount{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory GB per Core",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    (vmware_vm_mem_capacity_bytes{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} and on(vcenter, vmmo) vmware_vm_power_state{state=\"poweredOn\"})\n) / \nsum(\n   (vmware_host_cpu_corecount{ vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    (vmware_host_mem_capacity_bytes{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))\n) - \nsum(\n    vmware_host_mem_consumed_bytes{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Hosts Inventory",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_join(\n    label_replace(\n        vmware_host_software_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"},\n        \"build\", \"($1)\", \"build\", \"(.*)\"\n    ),\n    \"os\",\" \",\"software\",\"version\",\"build\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(vmware_host_cpu_corecount{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(vmware_host_cpu_capacity_hertz{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(vmware_host_mem_capacity_bytes{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))",
     "legendFormat": "__auto"
    },
    {
     "expr": "vmware_host_sys_uptime_seconds{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top VMs per CPU Used",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n  $top,\n  max_over_time(\n    (\n      vmware_vm_cpu_usage_hertz{vcenter=~\"$vcenter\"}\n        * on (vmmo) group_left\n          vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n    )[$__range:]\n  )\n)",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "Top VMs per Memory Used",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n  $top,\n  max_over_time(\n    (\n      vmware_vm_mem_consumed_bytes{vcenter=~\"$vcenter\"}\n        * on (vmmo) group_left\n          vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n    )[$__range:]\n  )\n)",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n  vmware_host_cpu_usage_hertz{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n) / \nsum(\n  (vmware_host_cpu_capacity_hertz{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0)) *\n  (vmware_host_cpu_corecount{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))\n) \n* 100",
     "legendFormat": "Usage"
    },
    {
     "expr": "(\navg(\n    vmware_host_cpu_latency_ratio{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n)\n) * 100",
     "legendFormat": "Latency"
    },
    {
     "expr": "(\navg(\n    sum(\n        rate(vmware_host_cpu_ready_seconds_total{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}[$__rate_interval])\n    ) /\n    sum(\n        (vmware_host_cpu_corecount{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))\n    ) \n)\n) * 100",
     "legendFormat": "Ready"
    },
    {
     "expr": "(\navg(\n    rate(vmware_host_cpu_costop_seconds_total{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}[$__rate_interval])\n)\n) * 100",
     "legendFormat": "Costop"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n    vmware_host_mem_consumed_bytes{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n) / \nsum(\n    (vmware_host_mem_capacity_bytes{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))\n)\n* 100",
     "legendFormat": "Consumed"
    },
    {
     "expr": "sum(\n    vmware_host_mem_active_bytes{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n) / \nsum(\n    (vmware_host_mem_capacity_bytes{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))\n)\n* 100",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(\n    vmware_host_mem_shared_bytes{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n)/ \nsum(\n    (vmware_host_mem_capacity_bytes{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))\n)\n* 100",
     "legendFormat": "Shared"
    },
    {
     "expr": "sum(\n    vmware_host_mem_balloon_bytes{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n)/ \nsum(\n    (vmware_host_mem_capacity_bytes{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))\n)\n* 100",
     "legendFormat": "Ballooned"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(vmware_host_net_receive_bytes_per_second{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\", pfinstance!~\"^vusb.*\"} * 8)",
     "legendFormat": "rx: {{pfinstance}} "
    },
    {
     "expr": "sum(vmware_host_net_transmit_bytes_per_second{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\", pfinstance!~\"^vusb.*\"} * -8)",
     "legendFormat": "tx: {{pfinstance}}"
    }
   ]
  },
  {
   "title": "Top VMs per Network Receive",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n  $top,\n  max_over_time(\n    (\n      sum(\n        vmware_vm_net_receive_bytes_per_second{\n          vcenter=~\"$vcenter\",\n          pfinstance!~\"^vmnic.*|^vusb.*\"\n        }\n      ) by (vm)\n        * on (vm) group_left\n          vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n    )[$__range:]\n  )\n) * 8",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "Top VMs per Network Transmit",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n  $top,\n  max_over_time(\n    (\n      sum(\n        vmware_vm_net_transmit_bytes_per_second{\n          vcenter=~\"$vcenter\",\n          pfinstance!~\"^vmnic.*|^vusb.*\"\n        }\n      ) by (vm)\n        * on (vm) group_left\n          vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n    )[$__range:]\n  )\n) * 8",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }, "repeat": "host" },
  {
   "title": "Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_host_cpu_corecount{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} * on (hostmo) group_left \nvmware_host_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\", host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CPU Speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_host_cpu_capacity_hertz{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} * on (hostmo) group_left \nvmware_host_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\", host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Running VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  (vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} * on (hostmo) group_left\n    vmware_host_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\", host=~\"$host\"})\n  and on(vcenter, vmmo) vmware_vm_power_state{state=\"poweredOn\"}\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_host_mem_capacity_bytes{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} * on (hostmo) group_left \nvmware_host_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\", host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  vmware_host_cpu_usage_hertz{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} * on (hostmo) group_left \n  vmware_host_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\", host=~\"$host\"}\n) /\nsum(\n  (\n    vmware_host_cpu_capacity_hertz{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} * on (hostmo) group_left \nvmware_host_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\", host=~\"$host\"}\n  ) * \n  (\n    vmware_host_cpu_corecount{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} * on (hostmo) group_left \nvmware_host_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\", host=~\"$host\"}\n  )\n) \n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    vmware_host_mem_consumed_bytes{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} * on (hostmo) group_left \nvmware_host_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\", host=~\"$host\"}\n) / \nsum( \n    vmware_host_mem_capacity_bytes{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} * on (hostmo) group_left \nvmware_host_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\", host=~\"$host\"}\n)\n* 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Overcommit",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  vmware_vm_cpu_corecount{vcenter=~\"$vcenter\"} * on (hostmo) group_left \n  vmware_host_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\", host=~\"$host\"}\n)\n/ \nvmware_host_cpu_threadcount{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} * on (hostmo) group_left\nvmware_host_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\", host=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Available",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    (\n        vmware_host_cpu_capacity_hertz{vcenter=~\"$vcenter\", host=~\"$host\"} *\n        vmware_host_cpu_corecount{vcenter=~\"$vcenter\", host=~\"$host\"} \n    ) - \n    (\n        vmware_host_cpu_usage_hertz{vcenter=~\"$vcenter\", host=~\"$host\"}\n    )\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory GB per Core",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    (vmware_vm_mem_capacity_bytes{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} and on(vcenter, vmmo) vmware_vm_power_state{state=\"poweredOn\"})\n) / \nsum(\n   (vmware_host_cpu_corecount{ vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} and on(vcenter, hostmo) (vmware_host_power_state{state=\"poweredOn\"} and on(vcenter, hostmo) vmware_host_connection_state{state=\"connected\"} and on(vcenter, hostmo) vmware_host_maintenance_mode == 0))\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_host_mem_capacity_bytes{vcenter=~\"$vcenter\", host=~\"$host\"}\n- \n(\n    vmware_host_mem_consumed_bytes{vcenter=~\"$vcenter\", host=~\"$host\"}\n)",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}